### ISSUE TITLE
How to add the plugin markdown-it-mermaid？

### ISSUE THREAD

**Issue by rhinenoir** [niemingzhao/hexo-renderer-markdown#1]
https://github.com/tylingsoft/markdown-it-mermaid

↑this one

how should I edit my _config.yml file?

**Comment by niemingzhao** [comment]
markdown-it-mermaid plugin depends on `yarn`. What you just should do is to install markdown-it-mermaid by using yarn --- `yarn install markdown-it-mermaid --save`, and build it if should. Then edit your `_config.yml` like this:
```yml
markdown:
    plugins:
        markdown-it-mermaid:   # params is not necessary here!
```
It should work now. I have not given it a try because I use `npm`. Sorry!
